# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdNewAdvertizer(object):
    def setupUi(self, AdNewAdvertizer):
        AdNewAdvertizer.setObjectName("AdNewAdvertizer")
        AdNewAdvertizer.resize(411, 388)
        AdNewAdvertizer.setStyleSheet("background-color: rgb(208, 207, 230);")
        self.centralwidget = QtWidgets.QWidget(AdNewAdvertizer)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 30, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 90, 68, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 140, 68, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 180, 68, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 220, 121, 17))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 320, 99, 27))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 320, 99, 27))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(180, 80, 191, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 120, 191, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 170, 191, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 210, 191, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 270, 111, 17))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 260, 191, 31))
        self.lineEdit_5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_5.setObjectName("lineEdit_5")
        AdNewAdvertizer.setCentralWidget(self.centralwidget)

        self.retranslateUi(AdNewAdvertizer)
        QtCore.QMetaObject.connectSlotsByName(AdNewAdvertizer)

    def retranslateUi(self, AdNewAdvertizer):
        _translate = QtCore.QCoreApplication.translate
        AdNewAdvertizer.setWindowTitle(_translate("AdNewAdvertizer", "MainWindow"))
        self.label.setText(_translate("AdNewAdvertizer", "Register New User"))
        self.label_2.setText(_translate("AdNewAdvertizer", "Name"))
        self.label_3.setText(_translate("AdNewAdvertizer", "Email"))
        self.label_4.setText(_translate("AdNewAdvertizer", "Contact"))
        self.label_5.setText(_translate("AdNewAdvertizer", "Username"))
        self.pushButton.setText(_translate("AdNewAdvertizer", "Save"))
        self.pushButton_3.setText(_translate("AdNewAdvertizer", "Cancel"))
        self.label_6.setText(_translate("AdNewAdvertizer", "Password"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdNewAdvertizer = QtWidgets.QMainWindow()
    ui = Ui_AdNewAdvertizer()
    ui.setupUi(AdNewAdvertizer)
    AdNewAdvertizer.show()
    sys.exit(app.exec_())
