# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Akshu\Desktop\Evaluator\err_add.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Error(object):
    def setupUi(self, Error):
        Error.setObjectName("Error")
        Error.resize(379, 131)
        self.label = QtWidgets.QLabel(Error)
        self.label.setGeometry(QtCore.QRect(40, 40, 321, 17))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Error)
        self.pushButton.setGeometry(QtCore.QRect(280, 80, 81, 31))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Error)
        QtCore.QMetaObject.connectSlotsByName(Error)

    def retranslateUi(self, Error):
        _translate = QtCore.QCoreApplication.translate
        Error.setWindowTitle(_translate("Error", "Dialog"))
        self.label.setText(_translate("Error", "Something Went Wrong.. Try Again"))
        self.pushButton.setText(_translate("Error", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Error = QtWidgets.QDialog()
    ui = Ui_Error()
    ui.setupUi(Error)
    Error.show()
    sys.exit(app.exec_())
